export const ADD_NEW_ORDER_REQUEST = "ADD_NEW_ORDER_REQUEST";
export const ADD_NEW_ORDER_SUCCESS = "ADD_NEW_ORDER_SUCCESS";
export const ADD_NEW_ORDER_FAIL = "ADD_NEW_ORDER_FAIL";
export const ADD_NEW_ORDER_RESET = "ADD_NEW_ORDER_RESET";

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL";
export const GET_ORDER_DETAILS_RESET = "GET_ORDER_DETAILS_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const MY_ORDERS_LIST_REQUEST = "MY_ORDERS_LIST_REQUEST";
export const MY_ORDERS_LIST_SUCCESS = "MY_ORDERS_LIST_SUCCESS";
export const MY_ORDERS_LIST_FAIL = "MY_ORDERS_LIST_FAIL";
export const MY_ORDERS_LIST_RESET = "MY_ORDERS_LIST_RESET";

export const ADMIN_ORDERS_LIST_REQUEST = "ADMIN_ORDERS_LIST_REQUEST";
export const ADMIN_ORDERS_LIST_SUCCESS = "ADMIN_ORDERS_LIST_SUCCESS";
export const ADMIN_ORDERS_LIST_FAIL = "ADMIN_ORDERS_LIST_FAIL";
export const ADMIN_ORDERS_LIST_RESET = "ADMIN_ORDERS_LIST_RESET";
